/*M!999999\- enable the sandbox mode */ 
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `wp_pmxi_posts` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `post_id` bigint(20) unsigned NOT NULL,
  `import_id` bigint(20) unsigned NOT NULL,
  `unique_key` text DEFAULT NULL,
  `product_key` text DEFAULT NULL,
  `iteration` bigint(20) NOT NULL DEFAULT 0,
  `specified` tinyint(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=131 DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (1,16152,0,'16152','16152',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (2,5085,0,'5085','5085',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (3,5107,0,'5107','5107',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (4,6314,0,'6314','6314',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (5,18910,0,'18910','18910',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (6,16079,0,'16079','16079',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (7,6460,0,'6460','6460',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (8,5246,0,'5246','5246',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (9,11886,0,'11886','11886',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (10,11852,0,'11852','11852',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (11,4557,1,'4557','4557',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (12,4603,1,'4603','4603',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (13,4635,1,'4635','4635',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (14,4952,1,'4952','4952',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (15,4989,1,'4989','4989',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (16,5014,1,'5014','5014',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (17,5064,1,'5064','5064',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (18,5085,1,'5085','5085',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (19,5100,1,'5100','5100',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (20,5107,1,'5107','5107',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (21,5125,1,'5125','5125',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (22,5143,1,'5143','5143',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (23,5186,1,'5186','5186',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (24,5220,1,'5220','5220',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (25,5246,1,'5246','5246',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (26,5656,1,'5656','5656',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (27,5692,1,'5692','5692',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (28,5723,1,'5723','5723',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (29,5768,1,'5768','5768',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (30,5795,1,'5795','5795',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (31,5821,1,'5821','5821',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (32,5853,1,'5853','5853',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (33,5902,1,'5902','5902',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (34,5935,1,'5935','5935',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (35,5960,1,'5960','5960',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (36,6100,1,'6100','6100',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (37,6162,1,'6162','6162',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (38,6264,1,'6264','6264',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (39,6289,1,'6289','6289',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (40,6314,1,'6314','6314',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (41,6343,1,'6343','6343',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (42,6374,1,'6374','6374',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (43,6396,1,'6396','6396',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (44,6460,1,'6460','6460',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (45,6491,1,'6491','6491',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (46,6524,1,'6524','6524',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (47,6568,1,'6568','6568',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (48,6602,1,'6602','6602',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (49,7157,1,'7157','7157',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (50,7976,1,'7976','7976',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (51,8012,1,'8012','8012',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (52,11788,1,'11788','11788',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (53,11798,1,'11798','11798',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (54,11852,1,'11852','11852',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (55,11886,1,'11886','11886',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (56,11901,1,'11901','11901',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (57,11937,1,'11937','11937',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (58,12243,1,'12243','12243',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (59,12260,1,'12260','12260',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (60,12277,1,'12277','12277',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (61,12294,1,'12294','12294',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (62,12312,1,'12312','12312',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (63,15627,1,'15627','15627',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (65,15631,1,'15631','15631',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (66,16079,1,'16079','16079',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (67,16152,1,'16152','16152',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (68,18883,1,'18883','18883',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (69,18884,1,'18884','18884',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (70,18893,1,'18893','18893',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (71,18894,1,'18894','18894',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (72,18910,1,'18910','18910',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (73,4557,2,'','',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (74,4603,2,'','',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (75,4635,2,'','',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (76,4952,2,'','',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (77,4989,2,'','',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (78,5014,2,'','',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (79,5064,2,'','',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (80,5085,2,'','',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (81,5100,2,'','',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (82,5125,2,'','',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (83,5143,2,'','',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (84,5186,2,'','',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (85,5220,2,'','',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (86,5246,2,'','',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (87,5656,2,'','',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (88,5692,2,'','',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (89,5723,2,'','',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (90,5768,2,'','',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (91,5795,2,'','',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (92,5821,2,'','',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (93,5853,2,'','',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (94,5902,2,'','',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (95,5935,2,'','',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (96,5960,2,'','',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (97,6100,2,'','',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (98,6162,2,'','',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (99,6264,2,'','',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (100,6289,2,'','',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (101,6314,2,'','',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (102,6343,2,'','',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (103,6374,2,'','',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (104,6396,2,'','',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (105,6460,2,'','',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (106,6491,2,'','',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (107,6524,2,'','',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (108,6568,2,'','',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (109,6602,2,'','',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (110,7157,2,'','',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (111,7976,2,'','',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (112,8012,2,'','',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (113,11788,2,'','',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (114,11798,2,'','',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (115,11852,2,'','',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (116,11886,2,'','',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (117,11901,2,'','',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (118,11937,2,'','',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (119,12243,2,'','',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (120,12260,2,'','',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (121,12277,2,'','',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (122,12294,2,'','',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (123,12312,2,'','',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (124,15627,2,'','',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (125,15629,2,'','',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (126,15631,2,'','',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (127,16079,2,'','',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (128,16152,2,'','',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (129,18894,2,'','',0,0);
INSERT INTO `wp_pmxi_posts` (`id`, `post_id`, `import_id`, `unique_key`, `product_key`, `iteration`, `specified`) VALUES (130,18910,2,'','',0,0);
